server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://thebox.planetmike.org:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: messages
      host: {{ services_fqdn }}
      __path__: /var/log/messages

  - targets:
      - localhost
    labels:
      job: logs
      host: {{ services_fqdn }}
      __path__: /var/log/*.log

  - targets:
    - localhost
    labels:
      job: secure
      host: {{ services_fqdn }}
      __path__: /var/log/secure
